Rock bug fix
vultouri03/CLE4-DakParkGame pull request #42
Opened 2023-06-19 13:37 UTC by figoria

2023-06-19 13:51 UTC, vultouri03 approved these changes

2023-06-20 08:18 UTC, soupremeleader requested changes

2023-06-20 08:18 UTC, soupremeleader commented on src/js/ObjectClasses/Characters/Player.js
> +        if  (localStorage.getItem('rock') !== 'true') {
if  (localStorage.getItem('rock') !== 'true') {        
} else if( (engine.input.keyboard.wasPressed(Input.Keys.Space) && localStorage.getItem('slingshot') === "true" && localStorage.getItem('inventorySlot') === "4")){

empty if statement is not great 

please replace with:
if( (engine.input.keyboard.wasPressed(Input.Keys.Space) && localStorage.getItem('slingshot') === "true" && localStorage.getItem('inventorySlot') === "4" && this.ammunitionAmount > 0)){

2023-06-20 11:12 UTC, soupremeleader approved these changes

2023-06-20 11:12 UTC, merged